const cartActionType = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CAR: "CLEAR_ITEM_FROM_CAR",
  ADD_QUANTITY: "ADD_QUANTITY",
  REMOVE_QUANTITY: "REMOVE_QUANTITY",
};

export default cartActionType;
